# Generated by Django 5.1 on 2025-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='sr_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
