# Generated by Django 5.1 on 2025-02-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_nonteachingstaff_sr_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(null=True, unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('professor_female', models.IntegerField(default=0)),
                ('professor_male', models.IntegerField(default=0)),
                ('associate_professor_female', models.IntegerField(default=0)),
                ('associate_professor_male', models.IntegerField(default=0)),
                ('assistant_professor_female', models.IntegerField(default=0)),
                ('assistant_professor_male', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
