# Generated by Django 5.1 on 2025-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_teachingstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(null=True, unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('boys_general', models.IntegerField(default=0)),
                ('boys_st', models.IntegerField(default=0)),
                ('boys_sc', models.IntegerField(default=0)),
                ('boys_sebc', models.IntegerField(default=0)),
                ('boys_ews', models.IntegerField(default=0)),
                ('girls_general', models.IntegerField(default=0)),
                ('girls_st', models.IntegerField(default=0)),
                ('girls_sc', models.IntegerField(default=0)),
                ('girls_sebc', models.IntegerField(default=0)),
                ('girls_ews', models.IntegerField(default=0)),
                ('total_boys', models.IntegerField(default=0)),
                ('total_girls', models.IntegerField(default=0)),
            ],
        ),
    ]
