# Generated by Django 5.1 on 2025-02-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_phdstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(null=True, unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('first_class', models.PositiveIntegerField(default=0)),
                ('second_class', models.PositiveIntegerField(default=0)),
                ('pass_class', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
