# Generated by Django 5.1 on 2025-02-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_department_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
