# Generated by Django 5.1 on 2025-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_teacherinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPublicationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ક્રમ', models.IntegerField()),
                ('શિક્ષકનું_નામ', models.CharField(max_length=255)),
                ('પ્રકાશિત_અથવા_અનુવાદિત_પુસ્તક_અથવા_અભ્યાસલેખ', models.CharField(max_length=500)),
                ('પ્રકાશક_અથવા_સામાયિક_નામ_વર્ષ_અંક_આવૃત્તિ', models.CharField(max_length=500)),
            ],
        ),
    ]
