# Generated by Django 5.1 on 2025-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_teacherpublicationinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ક્રમ', models.IntegerField()),
                ('શિક્ષકનું_નામ', models.CharField(max_length=255)),
                ('સંશોધન_પ્રોજેક્ટનું_શીર્ષક', models.CharField(max_length=255)),
                ('સંશોધન_ગ્રાંટ_આપનાર_સંસ્થા', models.CharField(max_length=255)),
                ('સંશોધન_મંજૂર_થેલ_કુલ_રકમ', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'સંશોધન પ્રોજેક્ટ માહિતી',
                'verbose_name_plural': 'સંશોધન પ્રોજેક્ટ માહિતી',
            },
        ),
    ]
