# Generated by Django 5.1 on 2025-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_researchprojectinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprojectinformation',
            name='સંશોધન_મંજૂર_થેલ_કુલ_રકમ',
            field=models.CharField(max_length=255),
        ),
    ]
