# Generated by Django 5.1 on 2025-02-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_researchprojectinformation_સ_શ_ધન_મ_જ_ર_થ_લ_ક_લ_રકમ'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Enter the special note text')),
                ('is_displayed', models.BooleanField(default=False, help_text='Check to display the note in the document')),
            ],
        ),
        migrations.AlterModelOptions(
            name='researchprojectinformation',
            options={},
        ),
    ]
