# Generated by Django 5.1 on 2025-02-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_specialproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialproject',
        ),
    ]
