# Generated by Django 5.1 on 2025-02-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_delete_specialproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Enter the special note text')),
                ('is_displayed', models.BooleanField(default=False, help_text='Check to display the note in the document')),
            ],
        ),
    ]
