# Generated by Django 5.1 on 2025-02-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_special_specialpro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'વર્ષ દરમ્યાન ભવનમાં રમત-ગમત/યુવક મહોત્સવ /એન.એસ.એસ. રાજ્ય/રાષ્ટ્રીય કક્ષાએ નોંધપાત્ર વિશિષ્ટસન્માન/પારિતોષિક મેળવ્યું હોય તો તેની સંક્ષિપ્ત વિગતો', 'verbose_name_plural': 'વર્ષ દરમ્યાન ભવનમાં રમત-ગમત/યુવક મહોત્સવ /એન.એસ.એસ. રાજ્ય/રાષ્ટ્રીય કક્ષાએ નોંધપાત્ર વિશિષ્ટસન્માન/પારિતોષિક મેળવ્યું હોય તો તેની સંક્ષિપ્ત વિગતો'},
        ),
        migrations.AlterModelOptions(
            name='specialnote',
            options={'verbose_name': 'વિશેષ નોંધ', 'verbose_name_plural': 'વિશેષ નોંધ'},
        ),
        migrations.AlterModelOptions(
            name='specialpro',
            options={'verbose_name': 'વર્ષ દરમ્યાન ભવનમાં કરેલા વિશિષ્ટ પ્રયોગો-પ્રોજેક્ટો વિષયક માહિતી સંક્ષેપમા', 'verbose_name_plural': 'વર્ષ દરમ્યાન ભવનમાં કરેલા વિશિષ્ટ પ્રયોગો-પ્રોજેક્ટો વિષયક માહિતી સંક્ષેપમા'},
        ),
    ]
