# Generated by Django 5.0.2 on 2025-03-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_alter_special_options_alter_specialnote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='nonteachingstaff',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='researchprojectinformation',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='special',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='specialnote',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='specialpro',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='teacherinformation',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='teacherpublicationinformation',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
        migrations.AddField(
            model_name='teachingstaff',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.year'),
        ),
    ]
