# Generated by Django 5.0.2 on 2025-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_year_course_year_examresult_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
