# Generated by Django 5.1 on 2025-03-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_alter_year_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinformation',
            old_name='કોન્ફરન્સ_પરિસંવાદ_કાર્યશાળા',
            new_name='conference',
        ),
        migrations.RenameField(
            model_name='teacherinformation',
            old_name='રજુ_કરેલા_અભ્યાસ_લેખનું_શીર્ષક',
            new_name='location_date',
        ),
        migrations.RenameField(
            model_name='teacherinformation',
            old_name='શિક્ષકનું_નામ_અને_હોદ્દો',
            new_name='paper_title',
        ),
        migrations.RenameField(
            model_name='teacherinformation',
            old_name='સ્થાન_અને_તારીખ',
            new_name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='teacherinformation',
            name='ક્રમ',
        ),
    ]
