# Generated by Django 5.1 on 2025-03-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_rename_ક_ન_ફરન_સ_પર_સ_વ_દ_ક_ર_યશ_ળ__teacherinformation_conference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherpublicationinformation',
            old_name='પ્રકાશક_અથવા_સામાયિક_નામ_વર્ષ_અંક_આવૃત્તિ',
            new_name='publication_title',
        ),
        migrations.RenameField(
            model_name='teacherpublicationinformation',
            old_name='પ્રકાશિત_અથવા_અનુવાદિત_પુસ્તક_અથવા_અભ્યાસલેખ',
            new_name='publisher_details',
        ),
        migrations.RenameField(
            model_name='teacherpublicationinformation',
            old_name='ક્રમ',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='teacherpublicationinformation',
            old_name='શિક્ષકનું_નામ',
            new_name='teacher_name',
        ),
    ]
