# Generated by Django 5.1 on 2025-03-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_rename_પ_રક_શક_અથવ__સ_મ_ય_ક_ન_મ_વર_ષ_અ_ક_આવ_ત_ત__teacherpublicationinformation_publication_title_and'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchprojectinformation',
            old_name='શિક્ષકનું_નામ',
            new_name='approved_amount',
        ),
        migrations.RenameField(
            model_name='researchprojectinformation',
            old_name='સંશોધન_ગ્રાંટ_આપનાર_સંસ્થા',
            new_name='funding_agency',
        ),
        migrations.RenameField(
            model_name='researchprojectinformation',
            old_name='સંશોધન_પ્રોજેક્ટનું_શીર્ષક',
            new_name='research_project_title',
        ),
        migrations.RenameField(
            model_name='researchprojectinformation',
            old_name='ક્રમ',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='researchprojectinformation',
            old_name='સંશોધન_મંજૂર_થેલ_કુલ_રકમ',
            new_name='teacher_name',
        ),
    ]
