# Generated by Django 5.1 on 2025-03-11 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_remove_teachingstaff_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phdstudent',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='phdstudent',
            name='sr_no',
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.department'),
        ),
    ]
