# Generated by Django 5.1 on 2025-03-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_remove_phdstudent_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaff',
            name='sr_no',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
