# Generated by Django 5.0 on 2025-05-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_researchprojectinformation_user_special_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchprojectinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='special',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specialnote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='specialpro',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherpublicationinformation',
            name='user',
        ),
    ]
